# Generated by Django 3.2.16 on 2022-12-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Books'},
        ),
    ]
