# Generated by Django 3.2.16 on 2022-12-20 00:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=17)),
                ('house_number', models.CharField(max_length=10)),
                ('postal_address', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('concluded', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('cart_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'ordering': ['-order_id'],
            },
        ),
    ]
