# Generated by Django 3.2.16 on 2022-12-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_orderset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderset',
            name='set_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
    ]
