# Generated by Django 3.2.16 on 2022-12-21 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderset',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='checkout.order'),
        ),
    ]
