# Generated by Django 3.2.16 on 2022-12-30 11:38

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20221230_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
