# Generated by Django 3.2.16 on 2022-12-19 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='session',
        ),
    ]
