# Generated by Django 3.2.16 on 2022-12-19 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_order_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
